name: kettle-dl2
channels:
  - conda-forge
  - pytorch
  - anaconda
dependencies:
  - cartopy=0.18.0
  - dask=2021.6.2
  - gsutil=4.64
  - h5netcdf=0.11.0
  - ipython=7.18.1
  - jupyter=1.0.0
  - jupyterlab=2.2.6
  - matplotlib=3.3.1
  - netcdf4=1.5.3
  - notebook=6.1.4
  - numpy=1.19.5
  - pandas=1.1.3
  - pip=20.2.4
  - python=3.8.5
  - scikit-image=0.17.2
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - seaborn=0.11.1
  - sqlite=3.33.0
  - tensorboard=2.5.0
  - xarray=0.18.2
  - pip:
    - geopandas==0.9.0
    - fiona==1.8.20
    - tensorflow==2.5.0
